

Import('rtconfig')
import os
from building import *

Import('SDK_ROOT')
Import('APP_ROOT')

path_inc = [APP_ROOT + '/common/inc']
path_inc += [APP_ROOT + '/common/sdk_demo/vlcview']
path_inc += [SDK_ROOT + '/extlib/inc/human_detect']
path_inc += [SDK_ROOT + '/extlib/inc']
path_inc += [SDK_ROOT + '/extlib']
path_inc += [SDK_ROOT + '/extlib/inc/isp']
path_inc += [SDK_ROOT + '/components/libc/minilibc']
path_inc += [SDK_ROOT + '/components/usb/include']
path_inc += [SDK_ROOT + '/components']
path_inc += [SDK_ROOT]

src	= Glob('*.c')
#src += Glob("../smart_enc/*.c")

#group = DefineGroup('sample_vlcview', src, depend = ['RT_USING_HUMAN_DETECT', 'RT_USING_SAMPLE_VLCVIEW', 'FH_USING_ADVAPI_MD'], LOCAL_CPPPATH = path_inc)
group = DefineGroup('sample_vlcview', src, depend = [], LOCAL_CPPPATH = path_inc)

Return('group')
